Repository Monest-eco/monest-ai, pull requests merged in 2021-12, with the labels that each got.

#8 #7 Setting up AI project
  .gitignore
  Dockerfile
  README.md
  requirements.txt
  src/ai/model/Model.py
  src/ai/model/__init__.py
  src/main.py
Labels: enhancement

#11 feat(): Adding h4py dependency into requirements.txt
  requirements.txt
Labels: AI research

#13 Creation of the first ML model
  src/ai/dataset/Dataset.py
  src/ai/dataset/__init__.py
  src/ai/exceptions/file/FileExtension.py
  src/ai/exceptions/file/IndexRange.py
  src/ai/exceptions/file/UnreadFile.py
  src/ai/exceptions/file/__init__.py
  src/ai/exceptions/model/InvalidNeurons.py
  src/ai/exceptions/model/InvalidShape.py
  src/ai/exceptions/model/LoadedModel.py
  src/ai/exceptions/model/NoCompilation.py
  src/ai/exceptions/model/NoHistory.py
  src/ai/exceptions/model/NoLayers.py
  src/ai/exceptions/model/NoSaveMode.py
  src/ai/exceptions/model/WrongActivation.py
  src/ai/exceptions/model/__init__.py
  src/ai/file/File.py
  src/ai/file/__init__.py
  src/ai/model/Model.py
  src/main.py
Labels: enhancement, AI research

#22 Units tests and bash scripts
  bin/test/t.h5
  launch.sh
  src/ai/file/File.py
  test.sh
  tests/ai_test.h5
  tests/backup_ai_cool.h5
  tests/dataset_test.py
  tests/datatest.json
  tests/file_test.py
Labels: AI research

#23 AI Fit
  src/ai/dataset/Dataset.py
  src/ai/model/Model.py
  src/main.py
Labels: AI research

#25 Abstract classes
  .gitignore
  src/ai/dataset/Dataset.py
  src/ai/dataset/DatasetJSON.py
  src/ai/dataset/__init__.py
  src/ai/exceptions/file/__init__.py
  src/ai/exceptions/model/InvalidCurve.py
  src/ai/exceptions/model/InvalidShape.py
  src/ai/exceptions/model/InvalidType.py
  src/ai/exceptions/model/__init__.py
  src/ai/file/__init__.py
  src/ai/model/Model.py
  src/ai/model/TensorflowModel.py
  src/ai/model/__init__.py
  src/ai/model/enums/TensorFlowEnum.py
  src/main.py
  tests/dataset_test.py
  tests/datatest.json
  tests/file_test.py
Labels: AI research

#28 Request class file
  src/ai/request/Request.py
Labels: AI research
